CREATE DATABASE lib;
USE lib;

CREATE TABLE STUDENT (
    STU_ID_NUM CHAR(10) UNIQUE NOT NULL PRIMARY KEY,
    STU_FNAME VARCHAR(50) NOT NULL,
    STU_LNAME VARCHAR(50) NOT NULL,
    STU_PHONE_NUM CHAR(11) NOT NULL,
    STU_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    CHECK (STU_PHONE_NUM REGEXP '^[0-9]{11}$')
);

CREATE TABLE LIBRARIAN (
    LIB_ID_NUM CHAR(5) UNIQUE NOT NULL PRIMARY KEY,
    LIB_FNAME VARCHAR(50) NOT NULL,
    LIB_LNAME VARCHAR(50) NOT NULL,
    LIB_PHONE_NUM CHAR(11) NOT NULL,
    LIB_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    CHECK (LIB_PHONE_NUM REGEXP '^[0-9]{11}$')
);

CREATE TABLE PUBLISHER (
    PUB_ID CHAR(5) UNIQUE NOT NULL PRIMARY KEY,
    PUB_NAME VARCHAR(50) UNIQUE NOT NULL,
    PUB_ADDRESS VARCHAR(50) NOT NULL
);

CREATE TABLE BOOKGENRE (
    GENRE_ID CHAR(3) UNIQUE NOT NULL PRIMARY KEY,
    GENRE_NAME VARCHAR(50) UNIQUE NOT NULL,
    GENRE_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE AUTHOR (
    AUTH_ID CHAR(5) UNIQUE NOT NULL PRIMARY KEY,
    AUTH_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE BOOK (
    BOOK_ID CHAR(13) UNIQUE NOT NULL PRIMARY KEY,
    BOOK_TITLE VARCHAR(50) NOT NULL,
    BOOK_AGE_RATING INT(2) NOT NULL,
    BOOK_STATUS ENUM('Available', 'Not Available') NOT NULL,
    PUB_ID CHAR(5) NOT NULL,
    GENRE_ID CHAR(3) NOT NULL,
    CHECK (BOOK_AGE_RATING BETWEEN 1 AND 99),
    FOREIGN KEY (PUB_ID) REFERENCES PUBLISHER(PUB_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES BOOKGENRE(GENRE_ID)
);

CREATE TABLE BOOKAUTHOR (
    AUTH_ID CHAR(5) NOT NULL,
    BOOK_ID CHAR(13) NOT NULL,
    PRIMARY KEY (AUTH_ID, BOOK_ID),
    FOREIGN KEY (AUTH_ID) REFERENCES AUTHOR(AUTH_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

CREATE TABLE RENTAL (
    RENT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RENT_DATE DATE NOT NULL,
    RENT_EXPIRY_DATE DATE NOT NULL,
    RENT_FINE DECIMAL(10,2) NULL,
    BOOK_ID CHAR(13) NOT NULL,
    STU_ID_NUM CHAR(10) NOT NULL,
    LIB_ID CHAR(5) NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    FOREIGN KEY (STU_ID_NUM) REFERENCES STUDENT(STU_ID_NUM),
    FOREIGN KEY (LIB_ID) REFERENCES LIBRARIAN(LIB_ID_NUM)
);
